dist: bionic

services:
  - docker

env:
  - PATH=$PATH:$(pwd)/riscv/bin

script:

  # Get simulator tools
  - docker pull ghdl/ghdl:buster-gcc-8.3.0

  # Get toolchain and repos
  - /bin/bash -c "chmod u+x .ci/install.sh && .ci/install.sh"

  # Check compliance
  - >
    docker run -t -v `pwd`:/mnt/data ghdl/ghdl:buster-gcc-8.3.0
    /bin/bash -c "export PATH=$PATH:/mnt/data/riscv/bin"
    /bin/bash -c "export"
    /bin/bash -c "chmod u+x /mnt/data/.ci/run_tests.sh && /mnt/data/.ci/run_tests.sh"

notifications:
  email:
    on_success: never
    on_failure: always
